module MaterialsJP
    ORB_PATIENCE = '忍耐のオーブ'
    ORB_JUSTICE = '正義のオーブ'
    ORB_PRUDENCE = '慎重のオーブ'
    ORB_HOPE = '希望のオーブ'
    ORB_LOVE = '慈愛のオーブ'
    ORB_TEMPERANCE = '節制のオーブ'
    ORB_SINCERITY = '誠実のオーブ'
    ORB_POEM = '原詩のオーブ'
    SEED_OF_EVOLUTION = '進化の種'
    FLAME_OF_EVOLUTION = '進化の炎'
    XS = '微'
    S = '小'
    M = '中'
    L = '大'
    XL = '超'
end