module Materials
    ORB_PATIENCE = 'Orb of Patience'
    ORB_JUSTICE = 'Orb of Justice'
    ORB_PRUDENCE = 'Orb of Prudence'
    ORB_HOPE = 'Orb of Hope'
    ORB_LOVE = 'Orb of Love'
    ORB_TEMPERANCE = 'Orb of Temperance'
    ORB_SINCERITY = 'Orb of Sincerity'
    ORB_POEM = 'Orb of Original Poem'
    SEED_OF_EVOLUTION = 'Seed of Evolution'
    FLAME_OF_EVOLUTION = 'Flame of Evolution'
    XS = 'XS'
    S = 'S'
    M = 'M'
    L = 'L'
    XL = 'XL'
end