module GeneralFieldsJP
    ROLE = '職種'
    WT = '武器'
    SERIES = 'シリーズ'
    STATUS = 'ステータス'
    LEVEL = 'LV'
    ATTK = '攻撃力'
    DEF = '防御力'
    ULT = '必殺技'
    ULT_NAME = '技名'
    ULT_COST = '消費'
    ULT_DESC = '効果'
    EFFECT = '効果'
    TRANS_SYMBOL = '※'
    ATTR = '属性'
    ATTR_DAMAGE = '属性効果値'
    ATTR_RESIST = '属性耐性値'
    PASSIVES = 'スキル'
    EVOLUTION = 'レベル10で覚えるスキル'
    XS = '微'
    S = '小'
    M = '中'
    L = '大'
    XL = '超'
end