module GeneralFields
    HEROID = 'heroID'
    MD = 'metadata'
    ROLE = 'role'
    WT = 'weaponType'
    SERIES = 'series'
    STATS = 'stats'
    ULT = 'ultimate'
    NAME = 'name'
    COST = 'cost'
    DESC = 'description'
    ATTR = 'attribute'
    DMG = 'damage'
    RESIST = 'resistance'
    PASSIVES = 'passives'
    EVO = 'evolution'
    BASE = 'base'
    NEXT = 'next'
    MATS = 'materials'
    IMGS = 'images'
    CAPTION = 'caption'
end